# Generated by Django 4.2.5 on 2023-11-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_data_d_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
